[package]
name = "histat"
version = "1.0.0"
edition = "2021"
license = "Zlib"
description = "Zsh history stats"
repository = "https://github.com/cheyao/histat.git"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dirs = "5.0.1"
